plan_itinerary:
  description: |
    Create a 7-day travel itinerary with daily plans, weather forecasts, hotel and restaurant suggestions, packing tips, and budget details. Use only plain text strings for tool inputs.
    parameters:
    - City: {city}
    - Trip Date: {travel_dates}
    - Interests: {interests}
  expected_output: |
    A complete 7-day itinerary covering daily activities, accommodations, dining, weather, packing, and budget.

gather_city_info:
  description: |
    Generate an in-depth city guide with attractions, events, cultural tips, daily activities, weather, and estimated costs. Use only plain text strings for tool inputs.
    parameters:
    - City: {city}
    - Trip Date: {travel_dates}
    - Interests: {interests}
  expected_output: |
    A city guide with key sights, customs, events, weather, and cost overview.